# Generated by Django 4.1.7 on 2023-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(max_length=50, null=True)),
                ('next_stage', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
