# Generated by Django 4.1.7 on 2023-03-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino_bot', '0002_stages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CubeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_uid', models.IntegerField(null=True)),
                ('bet', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
            ],
        ),
    ]
